#!/usr/bin/perl
use strict;
use warnings;

use CGI qw( header param redirect );
use JSON::PP qw( decode_json );
use File::Slurp qw( read_file write_file );

my $ACTION = param("action");

unless (defined $ACTION && $ACTION) {
    action_index();
    exit;
}

if ($ACTION eq "add") {
    action_add();
} elsif ($ACTION eq "delete") {
    action_delete();
}

exit;


sub action_index {
    html_header();
    print <<INDEX;
<form method="POST">
<a href="/cloud/" class="pull-left">&lsaquo; Home</a>
<input type="hidden" name="action" value="add">
<input type="text" name="url" placeholder="YouTube URL (e.g. https://www.youtube.com/watch?v=oEc-ESRjntg)" autofocus="autofocus">
</form>

<div class="container">
INDEX
    opendir my $dir, "/data" || die "opendir failed: $!";
    my @files = map { $_ } sort { -M $a <=> -M $b } map { "/data/$_" } grep { /\.json$/ } readdir $dir;
    closedir $dir;

    foreach my $file (@files) {
        my $json = read_file($file) || print "ERROR: $@";
        my $dump = eval { decode_json($json) };
        die "ERROR: $file $@" if $@;
        print json2html($dump);
    }
    print <<INDEX;
</div>
INDEX
    html_footer();
}


sub action_delete {
    my $id = param("id");
    unlink "/data/$id.json";
    print redirect("magic");
}

sub action_add {
    my $url = param("url");
    unless (defined $url && $url) {
        print redirect("?error=addmissing");
        return;
    }

    my $json = `/usr/local/bin/youtube-dl --dump-json "$url"`;
    my $dump = eval { decode_json($json) };
    unless (defined $dump->{id}) {
        print redirect("magic?error=addjson");
        return
    }

    write_file("/data/$dump->{id}.json", $json);
    print redirect("magic")
}

sub json2html {
    my $dump = shift;

    my $output = "";
    $output .= <<BODY;
    <h4>
        $dump->{title}

        <a class="pull-right" href="magic?action=delete&id=$dump->{id}">Remove</a>
    </h4>
    <a href="$dump->{webpage_url}"><img src="$dump->{thumbnail}"></a>
<ul>
BODY
    foreach my $format (@{$dump->{formats}}) {
        if (defined $format->{abr}) {
            $output .= qq(<li><a href="$format->{url}">$format->{abr}k $format->{ext} (audio)</a></li>);
        } elsif (defined $format->{width}) {
            $output .= qq(<li><a href="$format->{url}">$format->{width}x$format->{height} $format->{ext} (video)</a></li>);
        }
    }
    $output .= <<BODY;
</ul>
    <hr>
BODY

    return $output;
}

sub html_header {
    print <<HEADER;
<html>
<head>
<style>
html, body {
    margin: 0;
}
body {
    background-color: #eee;
    color: #333;
    font-family: sans-serif;
}

img {
    max-width: 480px;
}
hr {
    border: 10px solid #ddd;
    margin: 30px 0;
}
form {
    background: #ddd;
    padding: 25px;
    text-align: center;
}
input {
    font-size: 22px;
    padding: 10px;
    width: 80%;
    border-radius: 5px;
    border: 0;
}
ul {
    list-style: none;
    padding: 0;
}
ul > li {
    padding: 15px 20px;
    display: inline-block;

}
.container {
    padding: 10px;
}
.pull-right {
    float: right;
}
.pull-left {
    float: left;
}

</style>
</head>
<body>
HEADER
}

sub html_footer {
    print <<FOOTER;
</body>
</html>
FOOTER
}
